// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
      );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwb2d20YxMrRfuWYCW1x0uMwYFQT2EV0k',
    appId: '1:744909736497:web:6e29317670cdf5d98fe310',
    messagingSenderId: '744909736497',
    projectId: 'totteku',
    authDomain: 'totteku.firebaseapp.com',
    storageBucket: 'totteku.appspot.com',
    measurementId: 'G-617F3DYFM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACY-1JUjr9AiCRT4EFlu3sWL9tFeKWXYU',
    appId: '1:744909736497:android:dc3233cbe91b8cfa8fe310',
    messagingSenderId: '744909736497',
    projectId: 'totteku',
    storageBucket: 'totteku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMNVisr19Dohmj9-Dos2iwqT3hgq7jBM',
    appId: '1:744909736497:ios:8241758c7adf88578fe310',
    messagingSenderId: '744909736497',
    projectId: 'totteku',
    storageBucket: 'totteku.appspot.com',
    iosClientId: '744909736497-6sk5nt75h600mh753s7rvno0l7svj79r.apps.googleusercontent.com',
    iosBundleId: 'com.youwaku.test2',
  );
}
